# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.23-apache-buster-node-browsers-legacy
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ROOT_PASSWORD: ''
          - MYSQL_USER: admin
          - MYSQL_PASSWORD: password
          - MYSQL_DATABASE: SS_mysite
          - MYSQL_HOST: '127.0.0.1'

    working_directory: /var/www/html

    steps:
      - checkout
      - run:
          name: Install MySQL driver
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install zip bcmath pdo_mysql mysqli

      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      # Download and cache dependencies

      # composer cache
      - restore_cache:
          keys:
            # "composer.json" can be used if "composer.json"
            # is not committed to the repository.
            - composer-v2-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - composer-v2-
      - run: composer install -n --prefer-dist
      - run: composer vendor-expose
      - save_cache:
          key: composer-v2-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - resources

      # prepare the database
      - run: mv .circleci/.env.circleci .env
      - run: mkdir -p silverstripe-cache/artifacts
      - run: vendor/bin/sake dev/build flush=1

      - persist_to_workspace:
          root: /var/
          paths:
            - www/html
  test:
    docker:
      - image: circleci/php:7.3.23-apache-buster-node-browsers-legacy
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ROOT_PASSWORD: ''
          - MYSQL_USER: admin
          - MYSQL_PASSWORD: password
          - MYSQL_DATABASE: SS_mysite
          - MYSQL_HOST: '127.0.0.1'

    working_directory: /var/www/html

    steps:
      - run: sudo chown -R circleci /var/www/html
      - attach_workspace:
          at: /var/
      - run:
          name: Install MySQL driver
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install zip bcmath pdo_mysql mysqli
      - run: composer install -n --prefer-dist
      # run tests with phpunit
      - run: ./vendor/bin/phpunit --log-junit silverstripe-cache/artifacts/junit.xml
      - store_test_results:
          path: silverstripe-cache/artifacts
      - store_artifacts:
          path: silverstripe-cache/artifacts
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build